# Generated by Django 5.2.6 on 2025-10-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Punyanator', max_length=255),
        ),
    ]
