# Generated by Django 5.2.6 on 2025-11-27 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 27, 17, 15, 20, 979263, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
