# Generated by Django 5.2.5 on 2025-12-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_postimage_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
