# Generated by Django 5.2.5 on 2026-01-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='unknown2-svgrepo-com.svg', upload_to='pfp_images'),
        ),
    ]
