# Generated by Django 5.2.5 on 2026-03-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0010_alter_post_edited_alter_profile_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.CASCADE, to='BlogApp.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='pfp_images//unknown2-svgrepo-com.svg', upload_to='pfp_images'),
        ),
    ]
