# Generated by Django 5.2.5 on 2026-03-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0011_postimage_post_alter_profile_pfp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
    ]
