# Generated by Django 5.2.5 on 2026-03-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0012_remove_postimage_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='used_in_post',
            field=models.BooleanField(default=False),
        ),
    ]
